// <auto-generated>
//   Translation export 가 UI 문자열 시트에서 만든 파일. 손으로 고치지 말 것 (export 마다 다시 쓴다).
//   값은 키 이름의 해시라 시트에 키를 끼워 넣어도 기존 프리팹의 값이 바뀌지 않는다.
// </auto-generated>
using System;
using System.Collections.Generic;
using Translation.Unity;

namespace TranslationSample
{
    /// <summary> UI 문자열 키. 시트의 키 이름과 같다 </summary>
    public enum LocalKey
    {
        None = 0,
        Common_Confirm = 1260923491,  // 확인
        Common_Cancel = -575620081,  // 취소
        Title_Fleet = -121016882,  // 함대
        Title_Language = 465463088,  // 언어
        Fleet_Count = -148123137,  // 보유 함선 {0}척
        Ship_Power = 249401657,  // 전투력 {0}
        Enum_Rare = 355951109,  // 희귀
        Enum_Epic = -2134889984,  // 영웅
    }

    /// <summary> LocalKey 와 시트 키 문자열을 오간다</summary>
    public static partial class LocalKeys
    {
        public const int Count = 8;

        private static readonly Dictionary<int, string> Names = new Dictionary<int, string>(Count)
        {
            { 1260923491, "Common_Confirm" },
            { -575620081, "Common_Cancel" },
            { -121016882, "Title_Fleet" },
            { 465463088, "Title_Language" },
            { -148123137, "Fleet_Count" },
            { 249401657, "Ship_Power" },
            { 355951109, "Enum_Rare" },
            { -2134889984, "Enum_Epic" },
        };

        private static Dictionary<string, LocalKey> _byName;

        /// <summary> 시트 키 이름. enum 에 없는 값이면 null </summary>
        public static string Name(LocalKey key)
        {
            return Names.TryGetValue((int)key, out var name) ? name : null;
        }

        /// <summary> 시트 키 이름으로 찾는다. 없으면 false 와 None </summary>
        public static bool TryParse(string name, out LocalKey key)
        {
            if (_byName == null)
            {
                var map = new Dictionary<string, LocalKey>(Count, StringComparer.Ordinal);
                foreach (var pair in Names)
                    map[pair.Value] = (LocalKey)pair.Key;
                _byName = map;
            }

            if (name != null && _byName.TryGetValue(name, out key))
                return true;

            key = LocalKey.None;
            return false;
        }

        /// <summary> 전체 키. 순서는 시트 순서다 </summary>
        public static IEnumerable<LocalKey> All
        {
            get
            {
                foreach (var pair in Names)
                    yield return (LocalKey)pair.Key;
            }
        }
    }

    /// <summary> 글자를 꺼내는 자리. TranslationRuntime 을 LocalKey 로 감싼 것이다</summary>
    public static partial class Localization
    {
        public static string GetString(LocalKey key)
        {
            if (key == LocalKey.None)
                return string.Empty;

            return TranslationRuntime.Get(KeyName(key));
        }

        /// <summary> {0} {1} 자리에 args 를 넣는다 </summary>
        public static string GetString(LocalKey key, params object[] args)
        {
            if (key == LocalKey.None)
                return string.Empty;

            return TranslationRuntime.Format(KeyName(key), args);
        }

        public static string GetString(string key)
        {
            return TranslationRuntime.Get(key);
        }

        public static string GetString(string key, params object[] args)
        {
            return TranslationRuntime.Format(key, args);
        }

        public static bool TryGetString(LocalKey key, out string text)
        {
            return TranslationRuntime.TryGet(KeyName(key), out text);
        }

        public static bool TryGetString(string key, out string text)
        {
            return TranslationRuntime.TryGet(key, out text);
        }

        /// <summary> 다른 enum 값을 "Enum_값이름" 키로 찾는다 </summary>
        public static string GetStringByEnum<T>(T value) where T : Enum
        {
            return TranslationRuntime.Get("Enum_" + value);
        }

        /// <summary> enum 에 없는 값이면 숫자를 키로 넘겨 없는 키 처리(@표시)를 받는다 </summary>
        private static string KeyName(LocalKey key)
        {
            return LocalKeys.Name(key) ?? ((int)key).ToString();
        }
    }
}
